{% set name = "xtensor" %}
{% set version = "0.25.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xtensor-stack/xtensor/archive/{{ version }}.tar.gz
  sha256: 32d5d9fd23998c57e746c375a544edf544b74f0a18ad6bc3c38cbba968d5e6c7

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - xtl >=0.7.5,<0.8
  run:
    - xtl >=0.7.5,<0.8
  run_constrained:
    - xsimd >=11.0.0,<12

test:
  commands:
    - test -d ${PREFIX}/include/xtensor  # [unix]
    - test -f ${PREFIX}/include/xtensor/xarray.hpp  # [unix]
    - test -f ${PREFIX}/share/cmake/xtensor/xtensorConfig.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/xtensor/xtensorConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\xtensor\xarray.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\xtensor\xtensorConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\cmake\xtensor\xtensorConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://github.com/xtensor-stack/xtensor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The C++ tensor algebra library
  description: Multi dimensional arrays with broadcasting and lazy computing
  doc_url: https://xtensor.readthedocs.io
  dev_url: https://github.com/xtensor-stack/xtensor

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
    - davidbrochart
