{% set name = "xtensor" %}
{% set version = "0.16.2" %}
{% set sha256 = "411c8d62194e3f90f318a5455ed7f5af8f9f27a54dae502aa07186f5d971f4e9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xtensor/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - xtl >=0.4.9,<0.5
  run:
    - xtl >=0.4.9,<0.5

test:
  commands:
    - test -d ${PREFIX}/include/xtensor  # [unix]
    - test -f ${PREFIX}/include/xtensor/xarray.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor/xtensorConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor/xtensorConfigVersion.cmake  # [unix]
    # TODO: replace with %PREFIX%\Library with %LIBRARY_PREFIX%
    - if exist %PREFIX%\Library\include\xtensor\xarray.hpp (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\Library\lib\cmake\xtensorConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\Library\lib\cmake\xtensorConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The C++ tensor algebra library'
  description: 'Multi dimensional arrays with broadcasting and lazy computing'
  doc_url: http://xtensor.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
