travis:
  secure:
    BINSTAR_TOKEN: 0YoV2B1+7l9Fq1S0JNYm6tYppv/zr8WKrhcp+mJiCU/l/07AhpB8lojRRruLyQQY9ocdFBcILXkYVVrjzdJMlm3C8XeXRwsTV3oZIPoGE7WRw2TeS72ujKhOYRsm30LE/uZjMTh8AFHsUj5qyLqnWn/s52AnYYAhLqoByQ25I/S3OuA6hxKZGAkER5l2Oz8AITHUkkK4Z528vWSEMhkiThceWNyrKI3tWxqHF4ya5h8EDinlSFjVdLgTONKsYkkO5pxqhAqdBP1WlrCHVlgFCvow0O1dHDBWswwYAPWTM87U1lDrdbjdg0ceCs3bj3Vm7bZ8q/ehID+KbXtz8vtsTZck3zZx3GzY/LgWf0hLuPImJE/XJI2U9hcebcdhC9m7DbGQVlvzwANAk6OJO5atapiNLVgZSYBUL4QtNO3vuhrPkdCp3wJrg42BRko8djBm2usAfjSzivBCxexMVhH+oUioJo770bLj6zaASbiDxYd9Rtr8DcCukOfh/H3jsLMXMXacTDd1Rc63p1JF94ufV8eQhqUOuurTczpxKFyiAeBDyRvDRh+wmoOdjGo92Rzge8FpDP2oB3zZWMlavJ/qg7rDUlnA2xkI6LNHCo4eX5DimH2yN6QuwwO3fxCKRGpN0hzR0xfSd9pF1Vf/MEliwuc5CGMo5kZvO0NzTWBogCg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
