travis:
  secure:
    BINSTAR_TOKEN: iSdCmgWJDBRCyTsJnFHg7peeAtDBNFFzocBybY1MhJaZ5myGnq+6izDUtoxpg7qy4CWoYaD6nOMRlvuYCKPVyJ4bpqj5BHxILfhzz2Idgu+3usw7eaDL8Px1w3wal0oOtPxSM81uEa1J63gYD3fjm3gSXde2o5WRJ9sOprkyWRHHZJ6vbvbxqY/fVnEZ68gKPU3iSTkmeeFAavzFiDV3A+BXqarmlbvW4fHAWF1FO5Semashp2rb/y4G1wzQIOSbprj/XPkhRIGaQDwsd4UFX9NwUBQAFE3vFOCwmAp9okflm+Sv5KAI3EiVsyRYEtGe13XrXTi2+WHl2VkpT4Lz5Mbs7HEKIhUE8wCG6LNUkajg2xkwwAjg2Gr5H7AvusYSglKqnmHo2A8HZ2Zb5ar+2JDmzCRe+xZP4gNNqNy8wheZnqhvGvaDCudYMJdCdpMeYjIDFVbVemsPvSJHxjZ0QiYpLy8iH0AZ7ALfOSbIViqQh/PX70E4yi+boFJY/FunHmB/0VJjGk1+eMjiOno3zSMaLU9vMS6GCuKc9CifTChTkQzWUbLTINfd/ZGpO4+eUJzT2DF5xpPgo/Qzua5xUbKwWApAR2SNEONNPhVmJq2XxfBE7uwDuWJu4DrelXt8RucY9/hieFzKo6CM6eN2fjWHUaqTrEiQnFrCJXKTmTc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
