travis:
  secure:
    BINSTAR_TOKEN: 02ClWiZyHl29aOA6MWX3R2zT76ZqnBMxUktkkrm+ICu19g0gvgClaTVSpuSEDzz9rkxFMeJBWjcwcyMB7LXZZjzWf8iFZUw2zzVj67yx3EJeoIMGHSCIouYvaJLEQrMX5Uv3npFzhGE0k3SQlGuxZdCKFKgCTYuygPRoU3PcoIcldny0uO+KFO5Jhmwz50zSlo8H+xbscPZAzr/x7ls31otdWTZNHPy30LzXURC3l7voxdmXSTmb8godHeAEk/FVJ4rT8+W2T/xbzlTwNXkK37xjzAUCXjfTXJ7J26QJTptWJ+x+f0yEU4V518fNwzRYqXPVYMdSb2T1Mo3g3LIdtEKN2K41D7f4fboAobB5N6jU5iJZ60dj/azVnkkjn0VTUtgb/hs5b4c6CqOOCANk8T70/hchQCNRxEAl8GYEDFJhB2wo9F5iwUUWrNRojk0VtWuG5mnUk91nGNo210krfXagcUccwQlYzEofjiBj8A6B1NGioEQtBwO0tGxP1dESl8tYvLmRghEiSgGCwGF7C1/2Zxp4tTZvfT1smswHcVnEbNrs+WyVnDrI889cC3H9FAxrz8Kd0gA3P5WfKVe+lmLiNddwwPkwhEgRWNWUI5ibL2pGUwLihcMJfPT0+QnpOcPn3mn908yACqwIE5My5wuAW411FJJA2MNUc69SU8c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
