appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: h9xD8bmTUPw3vjyKbPaZp9GRiqB3cSETcHXzDjEUqn2x7NXdkze1TqJJJ5F50IJDJssqLVPXqkXcIb+0IkYIBBY5KavAyhI2hKrW7aKN/ekBo/0EdaTRhEh6JAWoF0SpqN9+XVNMvTxRPJ4f9VIowOZdBKIu1WhBZv00oTjsZe2sCo0yCwrQAWQQQAKxIYOvvSBYO7GIrpJE1Ej5ljUbFTwyr45sEBFd8RCwLyL3KbtIUr+zIB78WO2AO9SX+tE2mkvcekG88LaqNVK49kk0danW7p0t4IUi7IzsBIf/5kWuQS9MZKBDISUq5fp/mMdnKx+ug/FDebX5eefcc8K4UEjScG8nYTHOdNNF35Z3d1/qushw+I9zSDa3kKmDgmorx0HWQBidn6T9VvfFFAkAQEzjdPXDGG3fOGMdSdRhJCQ95oPk8G1hzk5zFcDdUOlbwT8qnKtAplfS7rlFztdTXjAOiLmbF+klgQkoadWqJ5EVMOmQv15r47SLxw3INuaFxyUG5pMytm3FvZpjtc9VUDN10HAWLezJK+O3g/6YdJzFp2Y6s82jDdLteCQSoPmqwrOMjWn0ds6rphHfanFtJX+BNf2Sz/ilk4r21CeekCZ6nBi4SD6CJv8NQ+rECZxarBGPpAuulMI1Yy/UhPVx9BuLiR3C/kgPCZ28R4ioR9g=}
provider:
  win: azure
conda_forge_output_validation: true
