travis:
  secure:
    BINSTAR_TOKEN: skhfnYZFogVCsM5ByKyZGDl4TWwIHI8F0etBK2HWqxrhNJTW27jIWwFxExotaEbxTrsAQVglynm65SyTQWew8kVb8GPv6rpdsnP/XwX7olnqcIbgHiSywVJup9nyIc0KoYjG2DtSHJBJ66HjoaZqnkukFEd2bQxuit+CDs8Rzq/AIBNVP10vXi5noimBlUW/hMxxsUqM9ftgmvRVB92ClBxNzpDJufoYr6lN5iQPg3QaKxxydvQMGrzYxWGAR1D0wMFvKx+xk2CNWRKMFzv00mGCOMWeOB15cO0oN9ZC6ZyfWycRk4eBdPa+hHGt7hULl4vVBC6rfW/4H2lzOKd9dRNyRjUMFpmJpyFkD8eY2vAfnYBzRqyZXCpBUiFPO10oOMeLjAzzAFFzAfeQ6WF+a5iMcEqTS8765xTA0LIa90X6jbz9XZXj+vIORBz0x1p4unJ6O46Fgq2CRpPMGUGJSBiHIwvnUjjIvYMTIStSaqbqwduC55TUHmBlazAI7CVr9N0i8HXR4EZdnw2GSEVpugWxAAHYwCOgqj5N8VOAQSk52mi6lrMJYwx7WeTUnLrw7+G+BCegZAwQcwVcm/GHSQjbnek61lhaTProBQIdA0NeBLrJbUJkSqKwBbgOym2OCJpQRtEApANHG53nVRtA2vQwZdof7l5gf4YhrKJ5UjU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
