travis:
  secure:
    BINSTAR_TOKEN: Z5AXBLkvQqr2/fs/mKn7xh3I8c8CjJlGx5sdFlo1cXb3xWvkfLBv4L3/EJw9QlP7zL4qqbpKyfelJLEzQrizt0nXlVOhaAaGlDfcfxEVnXq11TMAwuEc7blCg8x0gshJKS62sgL/x197yssk7MOtoAl2kCwegzxWMPmAs4/kpjHoHHdrNksQ8ykNP9pXoskJdgS5uXifhHnDc0gNzHTklLWccvmsdBME5vQZWKcWUxqPPNhht/8JJf7mSSU6RXq+5SebP/oFsJPv/14nKHIq894G03scbkBje7BuHUg0+nmpYNDVQRZta/1BCcnmkFrwaB7TtzUn3If0AEwZ554pcfIZcAkzBSBNty4UE9nhbmJfigGR9QJYgjdmTKNTahcZvIjOwyvgX5+vZQE5a4DY+NwtbnkVebst+kxDoEuIR3+KJ5r3+F4YJaJIosyxdeDBcS0Uilwv4Hzg2NbMWfjgC4+VxfCkrVfXgK/H4S7uBOGkSNhSa7SFDWX4ZAbXomGeqfdtQxbVDFvlyMH4hwvvBYDDw5SlcJjB0MrzehyR16KzColiuaNGIG2ZJEk+U5ILbcr/XhhmVohyzc9lkeYBpFuR7ThM+ztZ+qgU4u7RFEkQV8dpMZ6wECJB9cYYDiW2aWpBSaxfz3yA9KF01XD94WKD0+XmfdGP+T7CeXLDg6Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
